# Generated by Django 5.1.7 on 2025-06-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_password', models.CharField(max_length=50)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('student_email', models.EmailField(max_length=254, unique=True)),
                ('student_phone', models.IntegerField(unique=True)),
                ('student_address', models.TextField()),
            ],
        ),
    ]
