# Generated by Django 5.1.7 on 2025-06-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_teacher_alter_adminuser_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_subject',
            field=models.CharField(default='subject', max_length=20),
        ),
    ]
