# Generated by Django 5.1.7 on 2025-06-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_teacher_teacher_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_subject',
            field=models.CharField(max_length=20),
        ),
    ]
